<a href="https://colab.research.google.com/github/RKulagowska/Pandas/blob/main/03_Pandas_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
d = pd.date_range('20191101', periods = 10, freq='Y')

In [ ]:
r = np.random.randn(10,4)
df= pd.DataFrame(r, index= d, columns=list('ABCD'))
print(df)

                   A         B         C         D
2019-12-31 -0.450815  0.221801  1.039557  0.176580
2020-12-31  2.411074 -0.456046 -0.981901  0.479663
2021-12-31 -1.097186  0.319194  0.256200  0.621018
2022-12-31  0.570678  0.347806  0.579443  0.273941
2023-12-31  0.293959 -1.550489 -1.596677 -0.230203
2024-12-31  0.763385 -0.950743  2.181206  0.241572
2025-12-31 -1.522013  0.084703 -0.449849  0.960024
2026-12-31  0.485717  0.168331 -0.100281 -0.085976
2027-12-31 -0.020683 -0.715073 -0.688303  2.717764
2028-12-31 -0.333789 -0.510964  0.227111 -0.132510

In [ ]:
print(df['A'])

2019-12-31   -0.450815
2020-12-31    2.411074
2021-12-31   -1.097186
2022-12-31    0.570678
2023-12-31    0.293959
2024-12-31    0.763385
2025-12-31   -1.522013
2026-12-31    0.485717
2027-12-31   -0.020683
2028-12-31   -0.333789
Freq: A-DEC, Name: A, dtype: float64

In [ ]:
print(df[['A','B']])

                   A         B
2019-12-31 -0.450815  0.221801
2020-12-31  2.411074 -0.456046
2021-12-31 -1.097186  0.319194
2022-12-31  0.570678  0.347806
2023-12-31  0.293959 -1.550489
2024-12-31  0.763385 -0.950743
2025-12-31 -1.522013  0.084703
2026-12-31  0.485717  0.168331
2027-12-31 -0.020683 -0.715073
2028-12-31 -0.333789 -0.510964

In [ ]:
df[0:3]

                   A         B         C         D
2019-12-31 -0.450815  0.221801  1.039557  0.176580
2020-12-31  2.411074 -0.456046 -0.981901  0.479663
2021-12-31 -1.097186  0.319194  0.256200  0.621018

In [ ]:
df.iloc[:,-1:-2:-1]

                   D
2019-12-31  0.176580
2020-12-31  0.479663
2021-12-31  0.621018
2022-12-31  0.273941
2023-12-31 -0.230203
2024-12-31  0.241572
2025-12-31  0.960024
2026-12-31 -0.085976
2027-12-31  2.717764
2028-12-31 -0.132510

In [ ]:
df.iloc[0:3,-1:-3:-1]

                   D         C
2019-12-31  0.176580  1.039557
2020-12-31  0.479663 -0.981901
2021-12-31  0.621018  0.256200

In [ ]:
df

                   A         B         C         D
2019-12-31 -0.450815  0.221801  1.039557  0.176580
2020-12-31  2.411074 -0.456046 -0.981901  0.479663
2021-12-31 -1.097186  0.319194  0.256200  0.621018
2022-12-31  0.570678  0.347806  0.579443  0.273941
2023-12-31  0.293959 -1.550489 -1.596677 -0.230203
2024-12-31  0.763385 -0.950743  2.181206  0.241572
2025-12-31 -1.522013  0.084703 -0.449849  0.960024
2026-12-31  0.485717  0.168331 -0.100281 -0.085976
2027-12-31 -0.020683 -0.715073 -0.688303  2.717764
2028-12-31 -0.333789 -0.510964  0.227111 -0.132510

In [ ]:
df.iloc[:7:2,:-4:-2]

                   D         B
2019-12-31  0.176580  0.221801
2021-12-31  0.621018  0.319194
2023-12-31 -0.230203 -1.550489
2025-12-31  0.960024  0.084703

In [ ]:
df.iloc[::,:-4:-1]

                   D         C         B
2019-12-31  0.176580  1.039557  0.221801
2020-12-31  0.479663 -0.981901 -0.456046
2021-12-31  0.621018  0.256200  0.319194
2022-12-31  0.273941  0.579443  0.347806
2023-12-31 -0.230203 -1.596677 -1.550489
2024-12-31  0.241572  2.181206 -0.950743
2025-12-31  0.960024 -0.449849  0.084703
2026-12-31 -0.085976 -0.100281  0.168331
2027-12-31  2.717764 -0.688303 -0.715073
2028-12-31 -0.132510  0.227111 -0.510964

In [ ]:
df.iloc[::-3,-2:-5:-2]

                   C         A
2028-12-31  0.227111 -0.333789
2025-12-31 -0.449849 -1.522013
2022-12-31  0.579443  0.570678
2019-12-31  1.039557 -0.450815

In [ ]:
df.iloc[::-3,-2::-2]

                   C         A
2028-12-31  0.227111 -0.333789
2025-12-31 -0.449849 -1.522013
2022-12-31  0.579443  0.570678
2019-12-31  1.039557 -0.450815

In [ ]:
df.iloc[::-3,-1:-5:-3]

                   D         A
2028-12-31 -0.132510 -0.333789
2025-12-31  0.960024 -1.522013
2022-12-31  0.273941  0.570678
2019-12-31  0.176580 -0.450815